#ifndef MACHINE_STATE_H
#define MACHINE_STATE_H

// Enum values match those of HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE and
// HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE
#define MACHINE_STATE_COUNT 6
typedef enum {
  MACHINE_STATE_OPEN = 0,
  MACHINE_STATE_CLOSED = 1,
  MACHINE_STATE_OPENING = 2,
  MACHINE_STATE_CLOSING = 3,
  MACHINE_STATE_STOPPED = 4,
  MACHINE_STATE_UNKNOWN = 255,
} machine_state_t;

#endif /* MACHINE_STATE_H */
